### ISSUE TITLE
Passing L.Popup object on the message attribute causes infinite loop

### ISSUE THREAD

**Issue by Raptormstr** [tombatossals/angular-leaflet-directive#351]
The Leaflet API documentation says a Popup object can be passed to the bindPopup method and the angular-leaflet-directive will simple pass along anything other than a string during $compile.  However, if you actually try this

message: L.popup()

and then click on the marker, browser tab performance will almost stop and the following will be listed in the console:

RangeError: Maximum call stack size exceeded
    at new Boolean (native)
    at Boolean.toString (native)
    at isArray (http://127.0.0.1:9000/bower_components/angular/angular.js:596:19)
    at copy (http://127.0.0.1:9000/bower_components/angular/angular.js:851:11)
    at copy (http://127.0.0.1:9000/bower_components/angular/angular.js:875:28)
    at copy (http://127.0.0.1:9000/bower_components/angular/angular.js:858:23)
    at copy (http://127.0.0.1:9000/bower_components/angular/angular.js:875:28)
    at copy (http://127.0.0.1:9000/bower_components/angular/angular.js:858:23)
    at copy (http://127.0.0.1:9000/bower_components/angular/angular.js:875:28)
    at copy (http://127.0.0.1:9000/bower_components/angular/angular.js:858:23)

After some troubleshooting I think it happens when Angular tries to copy the markerData properties for the $watch <a href="https://github.com/tombatossals/angular-leaflet-directive/blob/master/src/directives/markers.js#L43">here</a>.  However, it only happens when you click on the marker and not during creation.

Stephen

**Comment by tombatossals** [comment]
Ok, I'm closing this issue then. Thanks for reporting and solving.
