### ISSUE TITLE
Infinite $digest on center because of floating point comparison error

### ISSUE THREAD

**Issue by sompylasar** [tombatossals/angular-leaflet-directive#398]
Repro on [examples/center](http://tombatossals.github.io/angular-leaflet-directive/#!/examples/center)
Click the `lng` increase button (input type number "up" arrow).

Console output:
```
Uncaught object angular.js:36
(anonymous function) angular.js:36
h.$digest angular.js:12070
h.$apply angular.js:12279
safeApply angular-leaflet-directive.min.js:32
(anonymous function) angular-leaflet-directive.min.js:31
o.Mixin.Events.fireEvent leaflet.js:6
o.Map.include._onPanTransitionStep leaflet.js:9
o.Mixin.Events.fireEvent leaflet.js:6
o.PosAnimation.o.Class.extend._onStep leaflet.js:9
(anonymous function) leaflet.js:6
Error: [$rootScope:infdig] http://errors.angularjs.org/1.2.15/$rootScope/infdig?p0=10&p1=%5B%5B%22fn%3…4375%2C%5C%22zoom%5C%22%3A4%2C%5C%22autoDiscover%5C%22%3Afalse%7D%22%5D%5D
    at Error (native)
    at http://tombatossals.github.io/angular-leaflet-directive/bower_components/angular/angular.min.js:6:450
    at h.$digest (http://tombatossals.github.io/angular-leaflet-directive/bower_components/angular/angular.min.js:106:438)
    at h.$apply (http://tombatossals.github.io/angular-leaflet-directive/bower_components/angular/angular.min.js:108:370)
    at safeApply (http://tombatossals.github.io/angular-leaflet-directive/dist/angular-leaflet-directive.min.js:32:12448)
    at Object.<anonymous> (http://tombatossals.github.io/angular-leaflet-directive/dist/angular-leaflet-directive.min.js:31:21616)
    at o.Mixin.Events.fireEvent (http://tombatossals.github.io/angular-leaflet-directive/bower_components/leaflet-dist/leaflet.js:6:5055)
    at o.Map.include._onPanTransitionStep (http://tombatossals.github.io/angular-leaflet-directive/bower_components/leaflet-dist/leaflet.js:9:22856)
    at o.Mixin.Events.fireEvent (http://tombatossals.github.io/angular-leaflet-directive/bower_components/leaflet-dist/leaflet.js:6:5055)
    at o.PosAnimation.o.Class.extend._onStep (http://tombatossals.github.io/angular-leaflet-directive/bower_components/leaflet-dist/leaflet.js:9:21163)
    at http://tombatossals.github.io/angular-leaflet-directive/bower_components/leaflet-dist/leaflet.js:6:513 angular.js:9563
```

Details from Angular error:
```
10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: [["fn: function (){var c=m(a);if(p.$modelValue!==c){var d=p.$formatters,e=d.length;for(p.$modelValue=c;e--;)c=d[e](c);p.$viewValue!==c&&(p.$viewValue=c,p.$render())}return c}; newVal: \"-1.8896484375\"; oldVal: \"-0.9228515625\"","fn: function (){var a=k(e);n(a,U[c])||(n(a,g)?p(e,a=U[c]):U[c]=a);return g=a}; newVal: {\"lat\":40.111688665595956,\"lng\":-0.9228515625,\"zoom\":4,\"autoDiscover\":false}; oldVal: {\"lat\":40.111688665595956,\"lng\":-1.8896484375,\"zoom\":4,\"autoDiscover\":false}","center; newVal: {\"lat\":40.111688665595956,\"lng\":-0.9228515625,\"zoom\":4,\"autoDiscover\":false}; oldVal: {\"lat\":40.111688665595956,\"lng\":-1.8896484375,\"zoom\":4,\"autoDiscover\":false}"],["fn: function (){var c=m(a);if(p.$modelValue!==c){var d=p.$formatters,e=d.length;for(p.$modelValue=c;e--;)c=d[e](c);p.$viewValue!==c&&(p.$viewValue=c,p.$render())}return c}; newVal: \"-0.9228515625\"; oldVal: \"-1.8896484375\"","fn: function (){var a=k(e);n(a,U[c])||(n(a,g)?p(e,a=U[c]):U[c]=a);return g=a}; newVal: {\"lat\":40.111688665595956,\"lng\":-1.8896484375,\"zoom\":4,\"autoDiscover\":false}; oldVal: {\"lat\":40.111688665595956,\"lng\":-0.9228515625,\"zoom\":4,\"autoDiscover\":false}","center; newVal: {\"lat\":40.111688665595956,\"lng\":-1.8896484375,\"zoom\":4,\"autoDiscover\":false}; oldVal: {\"lat\":40.111688665595956,\"lng\":-0.9228515625,\"zoom\":4,\"autoDiscover\":false}"],["fn: function (){var c=m(a);if(p.$modelValue!==c){var d=p.$formatters,e=d.length;for(p.$modelValue=c;e--;)c=d[e](c);p.$viewValue!==c&&(p.$viewValue=c,p.$render())}return c}; newVal: \"-1.8896484375\"; oldVal: \"-0.9228515625\"","fn: function (){var a=k(e);n(a,U[c])||(n(a,g)?p(e,a=U[c]):U[c]=a);return g=a}; newVal: {\"lat\":40.111688665595956,\"lng\":-0.9228515625,\"zoom\":4,\"autoDiscover\":false}; oldVal: {\"lat\":40.111688665595956,\"lng\":-1.8896484375,\"zoom\":4,\"autoDiscover\":false}","center; newVal: {\"lat\":40.111688665595956,\"lng\":-0.9228515625,\"zoom\":4,\"autoDiscover\":false}; oldVal: {\"lat\":40.111688665595956,\"lng\":-1.8896484375,\"zoom\":4,\"autoDiscover\":false}"],["fn: function (){var c=m(a);if(p.$modelValue!==c){var d=p.$formatters,e=d.length;for(p.$modelValue=c;e--;)c=d[e](c);p.$viewValue!==c&&(p.$viewValue=c,p.$render())}return c}; newVal: \"-0.9228515625\"; oldVal: \"-1.8896484375\"","fn: function (){var a=k(e);n(a,U[c])||(n(a,g)?p(e,a=U[c]):U[c]=a);return g=a}; newVal: {\"lat\":40.111688665595956,\"lng\":-1.8896484375,\"zoom\":4,\"autoDiscover\":false}; oldVal: {\"lat\":40.111688665595956,\"lng\":-0.9228515625,\"zoom\":4,\"autoDiscover\":false}","center; newVal: {\"lat\":40.111688665595956,\"lng\":-1.8896484375,\"zoom\":4,\"autoDiscover\":false}; oldVal: {\"lat\":40.111688665595956,\"lng\":-0.9228515625,\"zoom\":4,\"autoDiscover\":false}"],["fn: function (){var c=m(a);if(p.$modelValue!==c){var d=p.$formatters,e=d.length;for(p.$modelValue=c;e--;)c=d[e](c);p.$viewValue!==c&&(p.$viewValue=c,p.$render())}return c}; newVal: \"-1.8896484375\"; oldVal: \"-0.9228515625\"","fn: function (){var a=k(e);n(a,U[c])||(n(a,g)?p(e,a=U[c]):U[c]=a);return g=a}; newVal: {\"lat\":40.111688665595956,\"lng\":-0.9228515625,\"zoom\":4,\"autoDiscover\":false}; oldVal: {\"lat\":40.111688665595956,\"lng\":-1.8896484375,\"zoom\":4,\"autoDiscover\":false}","center; newVal: {\"lat\":40.111688665595956,\"lng\":-0.9228515625,\"zoom\":4,\"autoDiscover\":false}; oldVal: {\"lat\":40.111688665595956,\"lng\":-1.8896484375,\"zoom\":4,\"autoDiscover\":false}"]]
```

**Comment by nmccready** [comment]
this seems to have been fixed a while ago
