### ISSUE TITLE
Problem with Angular 1.3.0 and Angular-Leaflet 0.7.8

### ISSUE THREAD

**Issue by oO** [tombatossals/angular-leaflet-directive#498]
I'm getting the following error after upgrading from 1.2.26 to 1.3.0 on a map with multiple markers. When I revert back to 1.2.26 everything is normal. 

SyntaxError: Unexpected token ILLEGAL
    at Function (native)
    at $c (http://localhost:8081/lib/angular/angular.min.js:104:46)
    at dc.readIdent (http://localhost:8081/lib/angular/angular.min.js:185:352)
    at dc.lex (http://localhost:8081/lib/angular/angular.min.js:181:255)
    at db.parse (http://localhost:8081/lib/angular/angular.min.js:187:212)
    at http://localhost:8081/lib/angular/angular.min.js:107:456
    at h.$watch (http://localhost:8081/lib/angular/angular.min.js:117:152)
    at addMarkerWatcher (http://localhost:8081/lib/angular-leaflet-directive/dist/angular-leaflet-directive.js:2647:41)
    at Object.fn (http://localhost:8081/lib/angular-leaflet-directive/dist/angular-leaflet-directive.js:815:23)
    at h.$digest (http://localhost:8081/lib/angular/angular.min.js:120:461)

**Comment by jessertaylor** [comment]
Old issue - closing - please re open if you need to
